services:

  # This is the base image we build
  hlds:
    image: "hlds1110"
    restart: always
    user: "1000:1000" # <- IMPORTANT !! Change this to your UID:GID to fix potential permission issues !
    network_mode: host
    volumes:
      - ./config/cstrike:/server/cstrike 
      - ./config/cstrk10r:/server/cstrk10r
      - ./config/cstrk11r:/server/cstrk11r
      - ./config/cstrk13:/server/cstrk13 
      - ./config/cstrk71:/server/cstrk71
      - ./config/dmc:/server/dmc 
      - ./config/tfc:/server/tfc
    command:
      - -port 27015 -game cstrike +map de_dust2 +maxplayers 16